### ISSUE TITLE
How to add steps dynamically?

### ISSUE THREAD

**Issue by sy1995** [badrinathvm/StepperView#52]
The example only has let type.
How to add steps dynamically?
thx

**Comment by badrinathvm** [comment]
Hi @sy1995 , Thank you for checking out the project. I am looking over the issue, keep you posted shortly.

**Comment by badrinathvm** [comment]
@sy1995  Adopted the feature and released a new version ( https://cocoapods.org/pods/StepperView )

Here's the example on how to use it. 

https://github.com/badrinathvm/StepperView/blob/master/Example/StepperView/ExampleView9.swift

Have a wonderful day ahead.
