### ISSUE TITLE
WatchOS Segments not aligned in centre

### ISSUE THREAD

**Issue by bencallis** [badrinathvm/StepperView#60]
**Describe the bug**
The segments are no longer centred on the line.

**To Reproduce**
Run sample app with latest Xcode 12.2 on a WatchOS 7.1 S5/S6 simulator

**Expected behavior**
The line to be aligned in the centre of the segments

**Screenshots**

Screenshot of the sample app 
![Simulator Screen Shot - Apple Watch Series 5 - 40mm - 2020-11-22 at 21 06 38](https://user-images.githubusercontent.com/1911951/99917186-9e128680-2d06-11eb-81dc-8061b52540ce.png)

![Simulator Screen Shot - Apple Watch Series 5 - 40mm - 2020-11-22 at 21 02 48](https://user-images.githubusercontent.com/1911951/99917100-14fb4f80-2d06-11eb-911b-80907b55cdad.png)

**Info (please complete the following information):**
 - Device: Both simulator and device
 - OS: WatchOS 7.1 S5/S6 (40 or 44mm)
 - Pod Version: 1.5.2
 - Xcode Version 12.2

**Additional context**
It looks like it may be caused by some default padding in the latest version of SwiftUI? I have not looked into the source code yet to try and identify the problem.

**Comment by badrinathvm** [comment]
Thank you @bencallis , I will have a look and provide the fix shortly.

**Comment by bencallis** [comment]
I have just seen there is a new version 1.5.4 with some layout fixes. For a quick test I still think the issue is apparent in this new version.

I've had a brief look at the code and it appears to be related to the `xOffset` calculated on the `VerticalLineView`

**Comment by badrinathvm** [comment]
I am having a look over it right now and keep u posted shortly.

**Comment by badrinathvm** [comment]
Hi @bencallis, the issue has been fixed with [Stepper View 1.5.5](https://cocoapods.org/pods/StepperView), see the attached screenshot. Let me know if anything else needs to be addressed.
![Simulator Screen Shot - Apple Watch Series 6 - 44mm - 2021-01-17 at 13 46 28](https://user-images.githubusercontent.com/1479179/104858352-3aa27080-58d3-11eb-9a03-8fafd356045f.png)
