### ISSUE TITLE
How to use with horizontal scrollview

### ISSUE THREAD

**Issue by wong-kene** [badrinathvm/StepperView#66]
I need to use stepperview with 9 steps. So i need a scrollview because width of stepperview more than device width
i try to add scrollview but the result show blank view.
How to do this case?

Thanks

**Comment by badrinathvm** [comment]
Hi, @wong-kene  Thank you so much for checking out `StepperView` U need to set the `.frame(height: constantValue)` to get the component visible. See the below gif 

![ScrollView_StepperView](https://user-images.githubusercontent.com/1479179/106393471-1f903000-63ac-11eb-9c84-df7050e95364.gif)

**Comment by badrinathvm** [comment]
@wong-kene  Let me know if u need any more information. Happy to solve them again. Thank you so much for using `StepperView`. Also do let me know which app u are using so that I can add it to the readme. That will benefit everyone a lot.

**Comment by wong-kene** [comment]
hi @badrinathvm thaks for your response and sory for my late reply

i tried your code, it has been worked nicely on IOS 14. but not working on IOS 13, just show blank screen

**Comment by badrinathvm** [comment]
Let me check quickly on iOS13 and update you shortly.
