### ISSUE TITLE
Core Data and StepperView

### ISSUE THREAD

**Issue by rainald** [badrinathvm/StepperView#76]
I am having a hard time getting StepperView to work with Core Data objects. Is there a tutorial or is it possible to be pointed in the right direction?

**Comment by badrinathvm** [comment]
Hi @rainald, Thank you for checking out the library. Regarding the Core Data Objects, are u trying the populate each of the `steps` arrays with Core Data content? Please post the error and code snippet i will have look and provide the solution.

**Comment by rainald** [comment]
yes I am trying to figure out how to populate the steps arrays with Core Data Content.

I have tried:
ForEach(journals, id:\.uniqueIdentifier) { journal in
                            StepperView().addSteps([Text("\(journal.date!)")])
                        }

Error is: Fatal error: Index out of range

I have tried:

@State var verticalSteps = []

Then in my core data fetch:

var journals: FetchedResults<Journal> {
        journalFetch.wrappedValue
        verticalSteps = journal.map() { $0.date }
    }

**Comment by badrinathvm** [comment]
@rainald  .addSteps() , `.indicators()` are mandatory for StepperView,  and the count of `steps.count == indicator.count `

**Comment by badrinathvm** [comment]
Closing the issue as the solution is provided in the previous comment. Feel free to reopen if any further issue exists.
